name: 更新代理列表

permissions:
  contents: write

on:
  schedule:
    - cron: '0 23 * * *'  # 北京时间早上7点 (UTC 23:00)
    - cron: '0 11 * * *'  # 北京时间晚上7点 (UTC 11:00)
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # 保留历史，避免 push 被拒绝

    - name: 设置 Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: 抓取代理列表
      run: python generate_proxy_list.py

    - name: 提交更新
      run: |
        # 拉取远程最新代码
        git fetch origin main

        # 尝试 rebase，遇到冲突只保留 proxy.txt（ours）
        git rebase origin/main || true
        if [ -f proxy.txt ]; then
          git checkout --ours proxy.txt || true
          git add proxy.txt || true
          git rebase --continue || true
        fi

        # 提交更新
        git add proxy.txt
        if git diff --staged --quiet; then
          echo "没有新的代理数据更新"
        else
          git commit -m "自动更新代理列表 $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:main
        fi
