name: 更新代理列表

permissions:
  contents: write

on:
  schedule:
    - cron: '0 23 * * *'  # 北京时间早上7点 (UTC 23:00)
    - cron: '0 11 * * *'  # 北京时间晚上7点 (UTC 11:00)
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # 保留完整历史

    - name: 设置 Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"

    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: 抓取代理列表
      run: python generate_proxy_list.py

    - name: 更新 proxy.txt 并推送
      run: |
        # 拉取远程分支
        git fetch origin main
        git checkout main

        # 保留远程文件，覆盖 proxy.txt
        git checkout origin/main -- .    # 恢复远程版本
        git add proxy.txt                 # 保留本地生成的 proxy.txt

        # 检查是否有更新
        if git diff --staged --quiet; then
          echo "没有新的代理数据更新"
        else
          git commit -m "自动更新代理列表 $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
