name: 更新代理列表

# 添加权限配置
permissions:
  contents: write
  actions: read
  pull-requests: write
  issues: write
  repository-projects: write

on:
  schedule:
    # 每天早上7点和晚上7点更新代理列表（北京时间）
    - cron: '0 23 * * *'  # 北京时间早上7点 (UTC 23:00)
    - cron: '0 11 * * *'  # 北京时间晚上7点 (UTC 11:00)
  workflow_dispatch:
    # 允许手动触发

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: 抓取代理列表
      run: |
        python generate_proxy_list.py
        
    - name: 提交更新
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add proxy.txt
        if git diff --staged --quiet; then
          echo "没有新的代理数据更新"
        else
          git commit -m "自动更新代理列表 $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:main
        fi
