name: 更新代理列表

on:
  schedule:
    # 每天早上7点和晚上7点更新代理列表（北京时间）
    - cron: '0 23 * * *'  # 北京时间早上7点 (UTC 23:00)
    - cron: '0 11 * * *'  # 北京时间晚上7点 (UTC 11:00)
  workflow_dispatch:
    # 允许手动触发

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: 抓取代理列表
      run: |
        python generate_proxy_list.py
        
    - name: 提交更新
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add proxy.txt
        git diff --staged --quiet || git commit -m "自动更新代理列表 $(date '+%Y-%m-%d %H:%M:%S')"
        git push