name: 自动更新代理列表

permissions:
  contents: write

on:
  schedule:
    - cron: '0 23 * * *'  # 北京时间早上7点
    - cron: '0 11 * * *'  # 北京时间晚上7点
  workflow_dispatch:      # 允许手动触发

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出仓库
    - name: 检出仓库
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # 2. 配置 Git 用户
    - name: 配置 Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"

    # 3. 设置 Python
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 4. 安装依赖
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # 5. 抓取代理列表
    - name: 抓取代理列表
      run: python generate_proxy_list.py

    # 6. 提交更新 proxy.txt
    - name: 提交更新
      run: |
        set +e  # 避免 git 命令失败导致 workflow 中断

        git checkout main
        git fetch origin main

        # 恢复远程文件，但保留 proxy.txt
        git checkout origin/main -- .
        git add proxy.txt

        # 检查 proxy.txt 是否有更新
        if git diff --staged --quiet; then
          echo "没有新的代理数据更新"
        else
          git commit -m "自动更新代理列表 $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main --force || echo "git push 出现错误，但 workflow 不会失败"
        fi
